# Object-oriented programming

In this notebook, we'll encounter **objects** and their use in Python.

### At the end of this notebook, you'll be able to:
* Access attributes and execute methods of objects
* Define classes and recognize class definition syntax
* Understand how to manipulate instances of a class

<hr>

<font color='Red'><font size = 8>Everything in Python is an object.</font></font>

<font color='Orange'><font size = "10">Everything in Python is an object.</font></font>

<font color='Green'><font size = "10">Everything in Python is an object.</font></font>

<font color='Blue'><font size = "10">Everything in Python is an object.</font></font>

<font color='Purple'><font size = "10">Everything in Python is an object.</font></font>

**Objects** are an organization of data (**attributes**), with associated code to operate on that data (functions defined on the objects, called **methods**).

Syntax:
```
obj.method()
obj.attribute
```

> **Question for consideration**: Given what we’ve discussed in this course so far, if you wanted to store information about a date, how would you do so?

In [75]:
# Store information about a date here

date_string = 'birthday'

month = 'december'

date_dictionary = 2004

## Example object: Date
Date is **class** module that we can import from the built-in **module** [datetime](https://docs.python.org/3/library/datetime.html). Modules can contain any combination of functions, classes, or variables, that become accessible once we import them.

Let's use `date` to demonstrate the features of an object in Python.

In [76]:
# Import date from datetime module
from datetime import date

In [77]:
# Set the data we want to store in our date object
day = 5
month = 12
year = 2004

# Create a date object
my_date = date(year, month, day)
print(my_date)

2004-12-05


In [78]:
# Check what type of thing `my_date` is
type(my_date)

datetime.date

We can check what attributes and methods an object has by using `.` after your variable name. You can also check more generally for the object type by using `date.` Alternatively, you can use `dir()` to check.

**Attributes** maintain the object's state, simply returning information about the object to you (e.g., day, time, year).

In [79]:
my_date.day
my_date.year

2004

**Methods** are functions that belong to and operate on the object directly.

In [80]:
# Method to return what day of the week the date is
# Note the parentheses for methods.
my_date.weekday()

6

Many objects also have very useful operations associated with them. For example, date allows us to subtract to find the difference between two dates.

In [81]:
# Define a second date
birthdate = date(1980, 7, 29)

# Calculate the difference between times
time_diff = my_date - birthdate
print(time_diff.days,  "days") #in days
print(time_diff.days/365,"years") #in years

8895 days
24.36986301369863 years


## Methods for strings and lists

There are many methods for strings, [see a list here](https://www.w3schools.com/python/python_ref_string.asp).

For example, we can make strings upper or lower case.


In [82]:
# Make a string all lower case
'IMMA LET YOU FINISH'.lower()

'imma let you finish'

In [83]:
# Make a string all upper case
'wait a second'.upper()

'WAIT A SECOND'

In [84]:
# We need to re-assign my_string to a variable when using upper
my_string = 'neusci440'
'neusci440'.upper()

'NEUSCI440'

> **Check your understanding** What will the following code print out?

In [85]:
inputs = ['fIx', 'tYpiNg', 'lIkE', 'tHiS']
output = ''

for element in inputs:
    print(element)
    output = output + element.lower() + ' '
    print(output)

print('For loop is over')
output.capitalize()

fIx
fix 
tYpiNg
fix typing 
lIkE
fix typing like 
tHiS
fix typing like this 
For loop is over


'Fix typing like this '

We've already encountered several methods for lists, such as `append`. Another good one to know is `index`. [There are many list methods](https://www.w3schools.com/python/python_ref_list.asp).

In [86]:
my_list = ['cat','oppossum','dog','zebra']

my_list.sort(reverse=True)
my_list

['zebra', 'oppossum', 'dog', 'cat']

We can check the documentation using this syntax:

In [87]:
list.sort?

Signature: list.sort(self, /, *, key=None, reverse=False)
Docstring:
Sort the list in ascending order and return None.

The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
order of two equal elements is maintained).

If a key function is given, apply it once to each list item and sort them,
ascending or descending, according to their function values.

The reverse flag can be set to sort in descending order.
Type:      method_descriptor

> **Check your understanding** What will the following code print out?

In [88]:
list_string = ['a', 'c', 'd', 'b']
list_string.sort()
list_string.reverse()
list_string

['d', 'c', 'b', 'a']

### Modified "in place" or not?
**Note**: Some methods update the object directly (in place), whereas others return an updated version of the input.

In [89]:
# Reverse a list is in place
my_list = ['a', 'b', 'c']
my_list.reverse()

print(my_list)

['c', 'b', 'a']


In [90]:
# Dictionary keys is not in place
car_dict = {'brand': 'BMW', 'model': 'M5', 'year': 2019}

# Return the keys in the dictionary
out = car_dict.keys() 


In [91]:
# print keys
print(type(out))
print(out)

<class 'dict_keys'>
dict_keys(['brand', 'model', 'year'])


In [92]:
# car_dict has not changed
print(type(car_dict))
print(car_dict)

<class 'dict'>
{'brand': 'BMW', 'model': 'M5', 'year': 2019}


In [93]:
# pop is in place
car_dict.pop('brand')

'BMW'

In [94]:
# car_dict has changed
car_dict

{'model': 'M5', 'year': 2019}

<hr>

## Classes

**Date** above is a class that Python has already defined for us. As it turns out, we can define classes too! Writing your own classes isn't *necessary* but it is a useful way to create complex, custom objects with their own data & methods. 

A class is defined almost like a function, but using the `class` keyword, and the class definition usually contains a number of class method definitions (a function in a class).
* Each class method should have an argument `self` as its first argument. This object is a self-reference. You'll almost never see `self` outside of a class definition.
    * Why do you need `self`? It's a little strange, but think of it this way: *an object always passes itself as the first argument to any of its own methods.*
* Some class method names have special meaning. For example, `__init__` is a method that is invoked when the object is first created.
    * (Full list <a href="https://docs.python.org/2.0/ref/specialnames.html">here</a>)
    
Let's create `Dog` as an example class.

In [95]:
# Define a class with `class`. 
class Dog():
    
    # Class attributes for all Dogs
    sound = 'Woof'

    # Class methods for objects of type Dog
    # Self is a special parameter that refers to the object
    def speak(self):
        print(self.sound)

In [96]:
# create an instance of Dog
my_dog = Dog('Hubert')

# access sound attribute
my_dog.sound 
# use speak method
my_dog.speak()


TypeError: Dog() takes no arguments

In [67]:
# Initialize a group of dogs
pack_of_dogs = [Dog('Hubert'), Dog('Peach'), Dog('Oreo'), Dog('Mocha')]

# Write for loop so each dog can speak
for d in pack_of_dogs:
    d.speak()

Ruff
Ruff
Ruff
Ruff


We can also create **instance-specific attributes**. Below, we've added an `init method` (the code below with `__init__`) which will create the attribute `name` whenever this class is initialized. This will allow each Dog instance to have its own name. The init method is called every time we create an instance of our class.

**Note:** the order of methods and attributes does not matter, but it is conventional to have the init method first.

In [ ]:
class Dog():
    
    sound = 'Woof'
    
    # Initializer, allows us to specificy instance-specific attributes
    # leading and trailing double underscores indicates that this is special to Python
    def __init__(self,name):
        self.name = name

    def speak(self):
        print(self.sound)

In [68]:
# Initialize a dog
my_dog = Dog()
# what goes in the parentheses is defined in the __init__

    


TypeError: Dog.__init__() missing 1 required positional argument: 'name'

In [69]:
# Now, we need to give dog an init argument 'name'
my_dog = Dog('Hubert')
# If not, we will receive an error

<div class="alert alert-success">
    <b>Task</b>: In the cell below, check the two attributes of our <code>my_dog</code> instance of the <code>Dog</code> class.</div>

In [117]:
# Check attributes
my_dog.speak()
my_dog.name

Ruff


'hub'

We can also define methods that take inputs. These methods are written as functions!

Below, `speak` has been modified to be proportional to the number of squirrels.

In [114]:
class Dog():
    
    # Class attributes for all Dogs
    sound = 'Woof'
    
    # Initializer, allows us to specificy instance-specific attributes
    # leading and trailing double underscores indicates that this is special to Python
    def __init__(self,name):
        self.name = name
    
    # Squirrels is a time series of # of squirrels, which our dog sums
    def speak(self,squirrels):
        self.barks = sum(squirrels)
        


In [119]:
# Try your dog here
my_dog = Dog('Hubert')
my_dog.speak([3, 2, 7])
my_dog.barks



12

## Class Inheritance
Classes can also inherit other classes! 

In [102]:
# First we define a parent class, Brain:
class Brain(): 
    
    def __init__(self, size = None, folded = None):
        self.size = size
        self.folded = folded
        
    def print_info(self):
        folded_string = ''
        if not self.folded:
            folded_string = 'not'
        print('This brain is ' + self.size + ' and is ' + folded_string + ' folded.')
        
        
my_brain = Brain(size='large',folded=True)

my_brain.print_info()

This brain is large and is  folded.


Now that we've created our parent class, `Brain`, we can inherit it by placing it in the parentheses in our class definition. This is telling Python that a SheepBrain is a type of Brain. By doing this, SheepBrain has access to all of the data and methods defined in Brain.

`super()` allows us to access the parent class data & methods. We need to use this when we are inheriting a class.

In [103]:
class SheepBrain(Brain):
    
    def __init__(self, size = 'medium', folded = False):
        super().__init__(size, folded)
        
class HumanBrain(Brain):
    def __init__(self, size = 'large', folded = True):
        super().__init__(size, folded)

> **Check your understanding**: What will the following cell print out?

In [104]:
sheep = SheepBrain()
human = HumanBrain()

human.folded and sheep.folded

False

# Intro to Neuscitk

```neuscitk```, much like ```datetime```, is a class module. It contains one class - ```LabChartDataset``` - which encompasses many methods for working with our neural data. The import will look a little different than the ```date``` import because of this. 

The souce code for ```neuscitk``` is posted on the canvas if you are interested in exactly how it is working.

In [105]:
import neuscitk as ntk

We want to bring everything that ```neuscitk``` contains at once, so we use the ```as``` keyword, rather than ```from```. ```ntk``` can be any piece of text - it is an arbitrary name that we assign this class module so that we don't have to write out neuscitk every time. This is optional, but the classic way of using class modules. 

In [106]:
import neuscitk as asdf1234

import neuscitk

```neuscitk``` contains an initializer, methods, and attributes just like the examples we went over above. 

In [120]:
# neuscitk intitializer that loads the .mat file into the script and turns it into a dictionary. 
# The writer chose dictionary because it made it simplest for following methods to work.

dataset = ntk.LabChartDataset('neusci302_demo.mat')

The syntax of the initializer is 

```
variable name = shortcut.LabChartDataset('path to your .mat file')
```

The class contained in neuscitk is ```LabChartDataset```, so that is why the initializer contains that text. ```neuscitk``` is arbitrary name the writer gave to the script that contains all of the details of the class.

Our LabChartDataset object has methods and attributes. 

In [121]:
# Attribute of the LabChartDataset object - sampling rate. Returns the samples per second of the data

dataset.fs

np.float64(40000.0)

In [122]:
# Method that gets an individual 'block' of the data. A block is equivalent to a Page

dataset.get_block(1)

array([[-9.531250e-03, -1.130000e-02, -1.316250e-02, ..., -2.485000e-02,
        -2.410625e-02, -2.612500e-02],
       [ 1.237500e-03,  1.250000e-03,  1.306250e-03, ...,  3.206250e-03,
         3.225000e-03,  3.237500e-03],
       [-5.000000e-05, -6.250000e-06,  2.375000e-04, ..., -2.187500e-04,
        -1.687500e-04, -1.312500e-04]], shape=(3, 400000), dtype=float32)

In [123]:
# Each of the arrays in the above result represents one channel. To get just one channel at a time, index the result

dataset.get_block(1)[0]

array([-0.00953125, -0.0113    , -0.0131625 , ..., -0.02485   ,
       -0.02410625, -0.026125  ], shape=(400000,), dtype=float32)

In [124]:
# Method that concatenates multiple blocks, meaning stitching together the arrays one after another.

dataset.concat_blocks([1,2,3])

array([[-9.53125e-03, -1.13000e-02, -1.31625e-02, ..., -1.55000e-03,
        -2.94375e-03, -5.69375e-03],
       [ 1.23750e-03,  1.25000e-03,  1.30625e-03, ...,  3.20000e-03,
         3.21250e-03,  3.23125e-03],
       [-5.00000e-05, -6.25000e-06,  2.37500e-04, ..., -2.12500e-04,
        -1.68750e-04, -1.37500e-04]], shape=(3, 1200000), dtype=float32)

More about analysis pipelines using neuscitk later on! Or, check out the neuscitk tutorial posted on canvas (though it goes much further with coding than we have covered).

<hr>

## About this notebook
This notebook is largely derived from [UCSD COGS18 Materials](https://cogs18.github.io/materials/12-Classes.html#objects), created by Tom Donoghue & Shannon Ellis. 

Want to run this notebook as a slideshow? If you have Python (or Anaconda) follow <a href="http://www.blog.pythonlibrary.org/2018/09/25/creating-presentations-with-jupyter-notebook/">these instructions</a> to setup your computer with the RISE plugin.